# Generated by Django 2.0.5 on 2018-07-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0002_auto_20180714_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrikeFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameId', models.IntegerField(default=0)),
                ('gameId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='strike_frame', to='bowling.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='frame',
            name='isFinished',
        ),
        migrations.AddField(
            model_name='frame',
            name='thirdThrow',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='totalScore',
            field=models.IntegerField(default=0),
        ),
    ]
