# Generated by Django 2.0.5 on 2018-07-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0003_auto_20180715_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='addScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='currentScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='lastSpareIndex',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='frame',
            name='throwIndex',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
    ]
